version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gestion_etudiants
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgresData:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  backend:
    image: student-grades-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gestion_etudiants
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: rootroot
    networks:
      - mynetwork
    depends_on:
      - db
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"

  frontend:
    image: student-grades-frontend
    networks:
      - mynetwork
    depends_on:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:80"
      networks:
        - mynetwork
      depends_on:
        - frontend
        - backend
        - db

volumes:
  postgresData:
    driver: local

networks:
  mynetwork:
    driver: overlay
