apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: exam
spec:
  minAvailable: 1  # Au moins 1 pod doit etre disponible
  selector:
    matchLabels:
      app: backend
